const KEY="bar-tpv-v02";
const initial={users:["NATI","Carlos","Edu","Sandra","extra1"],active:"NATI",selectedTable:null,tables:Array.from({length:10},(_,i)=>({name:"Cuenta "+(i+1),items:[],open:false})),products:[{name:"Caña",price:2},{name:"Cerveza",price:2.2},{name:"Refresco",price:2},{name:"Café",price:1.5},{name:"Agua",price:1},{name:"Vino",price:2}],sales:[]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||initial;
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function euro(n){return n.toFixed(2).replace(".",",")+" €"}
function tableTotal(t){return t.items.reduce((s,x)=>s+x.price*x.qty,0)}
function selectTable(i){db.selectedTable=i;render()}
function add(i){const t=db.tables[db.selectedTable],p=db.products[i];if(!t)return;const x=t.items.find(x=>x.name===p.name);if(x)x.qty++;else t.items.push({name:p.name,price:p.price,qty:1});t.open=true;save()}
function changeQty(i,d){const t=db.tables[db.selectedTable],x=t.items[i];if(!x)return;x.qty+=d;if(x.qty<=0)t.items.splice(i,1);if(!t.items.length)t.open=false;save()}
function rename(){const i=db.selectedTable,t=db.tables[i],n=prompt("Nombre de la cuenta:",t.name);if(n&&n.trim()){t.name=n.trim();save()}}
function closeAccount(){const i=db.selectedTable,t=db.tables[i];if(!tableTotal(t)){alert("La cuenta está vacía.");return}if(confirm("¿Cerrar esta cuenta sin cobrar?")){t.items=[];t.open=false;db.selectedTable=null;save()}}
function charge(method){const i=db.selectedTable,t=db.tables[i],total=tableTotal(t);if(!total)return alert("La cuenta está vacía.");db.sales.push({date:new Date().toISOString(),total,method,table:t.name,user:db.active});t.items=[];t.open=false;db.selectedTable=null;save();alert("Cobrado: "+euro(total)+" · "+method)}
function addProduct(){if(db.active!=="NATI")return alert("Solo NATI puede administrar productos.");const n=prompt("Nombre del producto:");if(!n)return;const p=parseFloat(prompt("Precio (€):","2"));if(!Number.isFinite(p)||p<0)return alert("Precio no válido.");db.products.push({name:n.trim(),price:p});save()}
function editProduct(i){if(db.active!=="NATI")return;const p=db.products[i],n=prompt("Nombre:",p.name),v=prompt("Precio (€):",p.price);if(n&&Number.isFinite(parseFloat(v))){p.name=n.trim();p.price=parseFloat(v);save()}}
function deleteProduct(i){if(db.active!=="NATI")return;if(confirm("¿Eliminar "+db.products[i].name+"?")){db.products.splice(i,1);save()}}
function todayTotal(){const d=new Date().toISOString().slice(0,10);return db.sales.filter(x=>x.date.slice(0,10)===d).reduce((s,x)=>s+x.total,0)}
function render(){const a=document.getElementById("app");let t=db.selectedTable===null?null:db.tables[db.selectedTable];a.innerHTML='<header class="top"><h1>🍻 BAR TPV</h1><small>v0.2 · '+db.active+'</small></header><main class="wrap"><div class="section">Usuario</div><div class="users">'+db.users.map(u=>'<button class="user '+(u===db.active?"active":"")+'" onclick="db.active=\''+u+'\';save()">'+u+'</button>').join("")+'</div><div class="section">Cuentas</div><div class="tables">'+db.tables.map((x,i)=>'<button class="table" onclick="selectTable('+i+')"><strong>'+x.name+'</strong><span>'+ (x.open?"🟢 Abierta":"⚪ Libre")+'</span><div class="total">'+euro(tableTotal(x))+'</div></button>').join("")+'</div>'+(t?'<div class="card"><div class="bar"><h2>'+t.name+'</h2><button onclick="db.selectedTable=null;render()">✕</button></div><div class="products">'+db.products.map((p,i)=>'<button class="product" onclick="add('+i+')"><b>'+p.name+'</b><span class="price">'+euro(p.price)+'</span></button>').join("")+'</div><div class="section">Cuenta</div>'+ (t.items.length?t.items.map((x,i)=>'<div class="row"><span><b>'+x.name+'</b><br>'+euro(x.price)+' × '+x.qty+'</span><span class="qty"><button onclick="changeQty('+i+',-1)">−</button> '+x.qty+' <button onclick="changeQty('+i+',1)">+</button></span></div>').join(""):"<p>Sin productos.</p>")+'<h2>Total: '+euro(tableTotal(t))+'</h2><div class="bar"><button class="primary" onclick="charge(\'Efectivo\')">💵 Efectivo</button><button class="primary" onclick="charge(\'Tarjeta\')">💳 Tarjeta</button></div><div class="bar"><button onclick="rename()">✏️ Renombrar</button><button class="danger" onclick="closeAccount()">Cerrar sin cobrar</button></div></div>':'<div class="section">Productos</div><div class="products">'+db.products.map((p,i)=>'<button class="product" onclick="alert(\'Selecciona primero una cuenta\')"><b>'+p.name+'</b><span class="price">'+euro(p.price)+'</span></button>').join("")+'</div>'+(db.active==="NATI"?'<p><button class="primary" onclick="addProduct()">＋ Añadir producto</button></p>':"")+'<div class="section">Caja de hoy</div><div class="card"><b>'+euro(todayTotal())+'</b><br>'+db.sales.filter(x=>x.date.slice(0,10)===new Date().toISOString().slice(0,10)).length+' cobros registrados</div></main>'}
render();