const KEY="bar-tpv-v01";
const initial={users:["NATI","Carlos","Edu","Sandra","extra1"],active:"NATI",tables:Array.from({length:10},(_,i)=>({name:"Cuenta "+(i+1),items:[],open:false})),products:[{name:"Caña",price:2},{name:"Cerveza",price:2.2},{name:"Refresco",price:2},{name:"Café",price:1.5},{name:"Agua",price:1},{name:"Vino",price:2}],sales:[]};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||initial;
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}
function euro(n){return n.toFixed(2).replace(".",",")+" €"}
function tableTotal(t){return t.items.reduce((s,x)=>s+x.price*x.qty,0)}
function add(ti,pi){const p=db.products[pi],t=db.tables[ti],x=t.items.find(x=>x.name===p.name);if(x)x.qty++;else t.items.push({name:p.name,price:p.price,qty:1});t.open=true;save()}
function modal(ti){const t=db.tables[ti];document.body.insertAdjacentHTML("beforeend",'<div class="modal" id="modal"><div class="sheet"><div class="bar"><h2>'+t.name+'</h2><button onclick="closeModal()">✕</button></div><div id="lines"></div><h2>Total: '+euro(tableTotal(t))+'</h2><div class="bar"><button class="primary" onclick="charge('+ti+','Efectivo')">Cobrar efectivo</button><button class="primary" onclick="charge('+ti+','Tarjeta')">Cobrar tarjeta</button></div><button onclick="rename('+ti+')">Cambiar nombre</button></div></div>');drawLines(ti)}
function drawLines(ti){const t=db.tables[ti],e=document.getElementById("lines");if(!e)return;e.innerHTML=t.items.length?t.items.map((x,i)=>'<div class="row"><span>'+x.name+' × '+x.qty+'</span><span>'+euro(x.price*x.qty)+'</span></div>').join(""):"<p>Sin productos todavía.</p>"}
function closeModal(){document.getElementById("modal")?.remove()}
function charge(ti,method){const t=db.tables[ti],total=tableTotal(t);if(!total)return;db.sales.push({date:new Date().toISOString(),total,method,table:t.name});t.items=[];t.open=false;closeModal();save()}
function rename(ti){const n=prompt("Nombre de la cuenta:",db.tables[ti].name);if(n&&n.trim()){db.tables[ti].name=n.trim();save();}}
function addProduct(){if(db.active!=="NATI")return alert("Solo NATI puede administrar productos.");const n=prompt("Nombre del producto:");if(!n)return;const p=parseFloat(prompt("Precio (€):","2"));if(!Number.isFinite(p))return;db.products.push({name:n.trim(),price:p});save()}
function deleteProduct(i){if(db.active!=="NATI")return;db.products.splice(i,1);save()}
function render(){const a=document.getElementById("app");a.innerHTML='<header class="top"><h1>🍻 BAR TPV</h1><small>Versión 0.1 · datos guardados en este dispositivo</small></header><main class="wrap"><div class="section">Usuario</div><div class="users">'+db.users.map(u=>'<button class="user '+(u===db.active?"active":"")+'" onclick="db.active=\''+u+'\';save()">'+u+'</button>').join("")+'</div><div class="section">Cuentas</div><div class="tables">'+db.tables.map((t,i)=>'<button class="table" onclick="modal('+i+')"><strong>'+t.name+'</strong><span>'+ (t.open?"🟢 Abierta":"⚪ Libre")+'</span><div class="total">'+euro(tableTotal(t))+'</div></button>').join("")+'</div><div class="section">Productos</div><div class="products">'+db.products.map((p,i)=>'<button class="product" onclick="addToSelected('+i+')"><b>'+p.name+'</b><span class="price">'+euro(p.price)+'</span></button>').join("")+'</div>'+(db.active==="NATI"?'<p><button class="primary" onclick="addProduct()">＋ Añadir producto</button></p>':"")+'<div class="section">Caja</div><div class="card"><b>Ventas registradas: '+db.sales.length+'</b><br>Total vendido: '+euro(db.sales.reduce((s,x)=>s+x.total,0))+'</div></main>'}
let selected=null;
function addToSelected(pi){if(selected===null){selected=prompt("Escribe el número de cuenta (1-10):");const n=parseInt(selected)-1;if(n>=0&&n<10){add(n,pi);modal(n)}selected=null}else{add(parseInt(selected)-1,pi);selected=null}}
render();